steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.1:
        options:
          - '--shell=bash'
        files:
          - kc-init.sh

  - label: ":bash: Test"
    plugins:
      vital-software/docker-compose#vital-v2.5:
        run: test
